
// List of products to be displayed

products = [
    {
        id: 1001,
        name: "Maths",
        location: "London",
        price: 50,
        image: "Images/math.png",
        spaces: 5,
    },
    {
        id: 1002,
        name: "English",
        location: "Birmingham",
        price: 40,
        image: "Images/english.png",
        spaces: 5,
    },
    {
        id: 1003,
        name: "Physics",
        location: "Enfield",
        price: 45,
        image: "Images/science.jpeg",
        spaces: 5,
    },
    {
        id: 1004,
        name: "Chemistry",
        location: "Birmingham",
        price: 50,
        image: "Images/science.jpeg",
        spaces: 5,
    },
    {
        id: 1005,
        name: "French",
        location: "Brighton",
        price: 45,
        image: "Images/french.jpeg",
        spaces: 5,
    },
    {
        id: 1006,
        name: "Geography",
        location: "London",
        price: 50,
        image: "Images/geography.jpeg",
        spaces: 5,
    },
    {
        id: 1007,
        name: "Statistics",
        location: "Basildon",
        price: 50,
        image: "Images/math.png",
        spaces: 5,
    },
    {
        id: 1008,
        name: "IT",
        location: "London",
        price: 40,
        image: "Images/IT.png",
        spaces: 5,
    },
    {
        id: 1009,
        name: "History",
        location: "Bournemouth",
        price: 40,
        image: "Images/history.jpeg",
        spaces: 5,
    },
    {
        id: 1010,
        name: "Biology",
        location: "Birmingham",
        price: 45,
        image: "Images/science.jpeg",
        spaces: 5,
    }
]